service: squared

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-west-2
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: main.app
    packRequirements: false

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'